import key from "../../apiKey";
const fetchRecipeData = async (id, test, setData, setLoading, setError) => {
  const exampleData = {
    vegetarian: true,
    vegan: false,
    glutenFree: true,
    dairyFree: false,
    veryHealthy: false,
    cheap: false,
    veryPopular: false,
    sustainable: false,
    lowFodmap: false,
    weightWatcherSmartPoints: 1,
    gaps: "no",
    preparationMinutes: null,
    cookingMinutes: null,
    aggregateLikes: 1,
    healthScore: 5,
    creditsText: "Foodista.com – The Cooking Encyclopedia Everyone Can Edit",
    license: "CC BY 3.0",
    sourceName: "Foodista",
    pricePerServing: 47.38,
    extendedIngredients: [
      {
        id: 1117,
        aisle: "Milk, Eggs, Other Dairy",
        image: "plain-yogurt.jpg",
        consistency: "LIQUID",
        name: "yogurt",
        nameClean: "low fat plain yogurt",
        original: "200 milliliters low-fat yogurt",
        originalName: "low-fat yogurt",
        amount: 200.0,
        unit: "milliliters",
        meta: ["low-fat"],
        measures: {
          us: {
            amount: 7.004,
            unitShort: "fl. oz",
            unitLong: "fl. ozs",
          },
          metric: {
            amount: 200.0,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 14412,
        aisle: "Beverages",
        image: "water.png",
        consistency: "LIQUID",
        name: "water",
        nameClean: "water",
        original: "200 milliliters water",
        originalName: "water",
        amount: 200.0,
        unit: "milliliters",
        meta: [],
        measures: {
          us: {
            amount: 6.764,
            unitShort: "fl. oz",
            unitLong: "fl. ozs",
          },
          metric: {
            amount: 200.0,
            unitShort: "ml",
            unitLong: "milliliters",
          },
        },
      },
      {
        id: 31015,
        aisle: "Produce",
        image: "chili-peppers-green.jpg",
        consistency: "SOLID",
        name: "chilli",
        nameClean: "green chili pepper",
        original: "1 piece green chilli (chopped)",
        originalName: "green chilli (chopped)",
        amount: 1.0,
        unit: "piece",
        meta: ["green", "chopped", "()"],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 1.0,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 11677,
        aisle: "Produce",
        image: "shallots.jpg",
        consistency: "SOLID",
        name: "shallot",
        nameClean: "shallot",
        original: "1 piece shallot (chopped)",
        originalName: "shallot (chopped)",
        amount: 1.0,
        unit: "piece",
        meta: ["chopped", "()"],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "",
            unitLong: "",
          },
          metric: {
            amount: 1.0,
            unitShort: "",
            unitLong: "",
          },
        },
      },
      {
        id: 2014,
        aisle: "Spices and Seasonings",
        image: "ground-cumin.jpg",
        consistency: "SOLID",
        name: "roasted cumin seeds",
        nameClean: "cumin seeds",
        original: "teaspoon dry roasted cumin seeds",
        originalName: "dry roasted cumin seeds",
        amount: 1.0,
        unit: "teaspoon",
        meta: ["dry"],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
          metric: {
            amount: 1.0,
            unitShort: "tsp",
            unitLong: "teaspoon",
          },
        },
      },
      {
        id: 2004,
        aisle: "Spices and Seasonings",
        image: "bay-leaves.jpg",
        consistency: "SOLID",
        name: "corriander leaves",
        nameClean: "bay leaves",
        original: "1 tablespoon corriander leaves (chopped)",
        originalName: "corriander leaves (chopped)",
        amount: 1.0,
        unit: "tablespoon",
        meta: ["chopped", "()"],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
          metric: {
            amount: 1.0,
            unitShort: "Tbsp",
            unitLong: "Tbsp",
          },
        },
      },
      {
        id: 2047,
        aisle: "Spices and Seasonings",
        image: "salt.jpg",
        consistency: "SOLID",
        name: "salt",
        nameClean: "table salt",
        original: "a dash of salt",
        originalName: "salt",
        amount: 1.0,
        unit: "dash",
        meta: [],
        measures: {
          us: {
            amount: 1.0,
            unitShort: "dash",
            unitLong: "dash",
          },
          metric: {
            amount: 1.0,
            unitShort: "dash",
            unitLong: "dash",
          },
        },
      },
      {
        id: 10014412,
        aisle: "Frozen",
        image: "ice-cubes.png",
        consistency: "SOLID",
        name: "ice cubes",
        nameClean: "ice",
        original: "ice cubes",
        originalName: "ice cubes",
        amount: 4.0,
        unit: "servings",
        meta: [],
        measures: {
          us: {
            amount: 4.0,
            unitShort: "servings",
            unitLong: "servings",
          },
          metric: {
            amount: 4.0,
            unitShort: "servings",
            unitLong: "servings",
          },
        },
      },
    ],
    id: 660959,
    title: "Spiced Lassi",
    readyInMinutes: 45,
    servings: 4,
    sourceUrl: "https://www.foodista.com/recipe/468J2KYB/spiced-lassi",
    image: "https://img.spoonacular.com/recipes/660959-556x370.jpg",
    imageType: "jpg",
    nutrition: {
      nutrients: [
        {
          name: "Calories",
          amount: 43.6,
          unit: "kcal",
          percentOfDailyNeeds: 2.18,
        },
        {
          name: "Fat",
          amount: 0.96,
          unit: "g",
          percentOfDailyNeeds: 1.48,
        },
        {
          name: "Saturated Fat",
          amount: 0.54,
          unit: "g",
          percentOfDailyNeeds: 3.36,
        },
        {
          name: "Carbohydrates",
          amount: 6.04,
          unit: "g",
          percentOfDailyNeeds: 2.01,
        },
        {
          name: "Net Carbohydrates",
          amount: 5.29,
          unit: "g",
          percentOfDailyNeeds: 1.92,
        },
        {
          name: "Sugar",
          amount: 4.52,
          unit: "g",
          percentOfDailyNeeds: 5.03,
        },
        {
          name: "Cholesterol",
          amount: 3.11,
          unit: "mg",
          percentOfDailyNeeds: 1.04,
        },
        {
          name: "Sodium",
          amount: 90.4,
          unit: "mg",
          percentOfDailyNeeds: 3.93,
        },
        {
          name: "Alcohol",
          amount: 0.0,
          unit: "g",
          percentOfDailyNeeds: 100.0,
        },
        {
          name: "Alcohol %",
          amount: 0.0,
          unit: "%",
          percentOfDailyNeeds: 100.0,
        },
        {
          name: "Protein",
          amount: 3.0,
          unit: "g",
          percentOfDailyNeeds: 6.0,
        },
        {
          name: "Calcium",
          amount: 109.08,
          unit: "mg",
          percentOfDailyNeeds: 10.91,
        },
        {
          name: "Phosphorus",
          amount: 81.37,
          unit: "mg",
          percentOfDailyNeeds: 8.14,
        },
        {
          name: "Vitamin B2",
          amount: 0.12,
          unit: "mg",
          percentOfDailyNeeds: 6.81,
        },
        {
          name: "Vitamin B12",
          amount: 0.29,
          unit: "µg",
          percentOfDailyNeeds: 4.83,
        },
        {
          name: "Potassium",
          amount: 153.62,
          unit: "mg",
          percentOfDailyNeeds: 4.39,
        },
        {
          name: "Manganese",
          amount: 0.08,
          unit: "mg",
          percentOfDailyNeeds: 3.89,
        },
        {
          name: "Iron",
          amount: 0.66,
          unit: "mg",
          percentOfDailyNeeds: 3.69,
        },
        {
          name: "Zinc",
          amount: 0.54,
          unit: "mg",
          percentOfDailyNeeds: 3.59,
        },
        {
          name: "Magnesium",
          amount: 13.6,
          unit: "mg",
          percentOfDailyNeeds: 3.4,
        },
        {
          name: "Vitamin B5",
          amount: 0.32,
          unit: "mg",
          percentOfDailyNeeds: 3.24,
        },
        {
          name: "Vitamin C",
          amount: 2.54,
          unit: "mg",
          percentOfDailyNeeds: 3.07,
        },
        {
          name: "Fiber",
          amount: 0.76,
          unit: "g",
          percentOfDailyNeeds: 3.02,
        },
        {
          name: "Vitamin B6",
          amount: 0.06,
          unit: "mg",
          percentOfDailyNeeds: 2.89,
        },
        {
          name: "Selenium",
          amount: 1.82,
          unit: "µg",
          percentOfDailyNeeds: 2.61,
        },
        {
          name: "Folate",
          amount: 8.77,
          unit: "µg",
          percentOfDailyNeeds: 2.19,
        },
        {
          name: "Vitamin B1",
          amount: 0.03,
          unit: "mg",
          percentOfDailyNeeds: 1.98,
        },
        {
          name: "Copper",
          amount: 0.04,
          unit: "mg",
          percentOfDailyNeeds: 1.78,
        },
        {
          name: "Vitamin A",
          amount: 63.93,
          unit: "IU",
          percentOfDailyNeeds: 1.28,
        },
      ],
      properties: [
        {
          name: "Glycemic Index",
          amount: 8.75,
          unit: "",
        },
        {
          name: "Glycemic Load",
          amount: 0.26,
          unit: "",
        },
        {
          name: "Inflammation Score",
          amount: -1.0,
          unit: "",
        },
        {
          name: "Nutrition Score",
          amount: 3.1578260880449545,
          unit: "%",
        },
      ],
      flavonoids: [
        {
          name: "Cyanidin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Petunidin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Delphinidin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Malvidin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Pelargonidin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Peonidin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Catechin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Epigallocatechin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Epicatechin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Epicatechin 3-gallate",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Epigallocatechin 3-gallate",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Theaflavin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Thearubigins",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Eriodictyol",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Hesperetin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Naringenin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Apigenin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Luteolin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Isorhamnetin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Kaempferol",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Myricetin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Quercetin",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Theaflavin-3,3'-digallate",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Theaflavin-3'-gallate",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Theaflavin-3-gallate",
          amount: 0.0,
          unit: "",
        },
        {
          name: "Gallocatechin",
          amount: 0.0,
          unit: "",
        },
      ],
      ingredients: [
        {
          id: 1117,
          name: "yogurt",
          amount: 50.0,
          unit: "milliliters",
          nutrients: [
            {
              name: "Choline",
              amount: 7.87,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Alcohol",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 100.0,
            },
            {
              name: "Vitamin B1",
              amount: 0.02,
              unit: "mg",
              percentOfDailyNeeds: 1.98,
            },
            {
              name: "Poly Unsaturated Fat",
              amount: 0.02,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Fat",
              amount: 0.8,
              unit: "g",
              percentOfDailyNeeds: 1.48,
            },
            {
              name: "Cholesterol",
              amount: 3.11,
              unit: "mg",
              percentOfDailyNeeds: 1.04,
            },
            {
              name: "Vitamin B12",
              amount: 0.29,
              unit: "µg",
              percentOfDailyNeeds: 4.83,
            },
            {
              name: "Calcium",
              amount: 94.75,
              unit: "mg",
              percentOfDailyNeeds: 10.91,
            },
            {
              name: "Selenium",
              amount: 1.71,
              unit: "µg",
              percentOfDailyNeeds: 2.61,
            },
            {
              name: "Phosphorus",
              amount: 74.56,
              unit: "mg",
              percentOfDailyNeeds: 8.14,
            },
            {
              name: "Vitamin B3",
              amount: 0.06,
              unit: "mg",
              percentOfDailyNeeds: 0.52,
            },
            {
              name: "Net Carbohydrates",
              amount: 3.65,
              unit: "g",
              percentOfDailyNeeds: 1.92,
            },
            {
              name: "Vitamin D",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Folic Acid",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Folate",
              amount: 5.7,
              unit: "µg",
              percentOfDailyNeeds: 2.19,
            },
            {
              name: "Vitamin K",
              amount: 0.1,
              unit: "µg",
              percentOfDailyNeeds: 0.17,
            },
            {
              name: "Copper",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 1.78,
            },
            {
              name: "Iron",
              amount: 0.04,
              unit: "mg",
              percentOfDailyNeeds: 3.69,
            },
            {
              name: "Magnesium",
              amount: 8.8,
              unit: "mg",
              percentOfDailyNeeds: 3.4,
            },
            {
              name: "Lycopene",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Vitamin B5",
              amount: 0.31,
              unit: "mg",
              percentOfDailyNeeds: 3.24,
            },
            {
              name: "Manganese",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 3.89,
            },
            {
              name: "Fluoride",
              amount: 6.21,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Protein",
              amount: 2.72,
              unit: "g",
              percentOfDailyNeeds: 6.0,
            },
            {
              name: "Fiber",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 3.02,
            },
            {
              name: "Vitamin B2",
              amount: 0.11,
              unit: "mg",
              percentOfDailyNeeds: 6.81,
            },
            {
              name: "Sodium",
              amount: 36.24,
              unit: "mg",
              percentOfDailyNeeds: 3.93,
            },
            {
              name: "Mono Unsaturated Fat",
              amount: 0.22,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Vitamin E",
              amount: 0.02,
              unit: "mg",
              percentOfDailyNeeds: 0.23,
            },
            {
              name: "Carbohydrates",
              amount: 3.65,
              unit: "g",
              percentOfDailyNeeds: 2.01,
            },
            {
              name: "Vitamin B6",
              amount: 0.03,
              unit: "mg",
              percentOfDailyNeeds: 2.89,
            },
            {
              name: "Sugar",
              amount: 3.65,
              unit: "g",
              percentOfDailyNeeds: 5.03,
            },
            {
              name: "Zinc",
              amount: 0.46,
              unit: "mg",
              percentOfDailyNeeds: 3.59,
            },
            {
              name: "Saturated Fat",
              amount: 0.52,
              unit: "g",
              percentOfDailyNeeds: 3.36,
            },
            {
              name: "Vitamin A",
              amount: 26.41,
              unit: "IU",
              percentOfDailyNeeds: 1.28,
            },
            {
              name: "Vitamin C",
              amount: 0.41,
              unit: "mg",
              percentOfDailyNeeds: 3.07,
            },
            {
              name: "Potassium",
              amount: 121.16,
              unit: "mg",
              percentOfDailyNeeds: 4.39,
            },
            {
              name: "Calories",
              amount: 32.62,
              unit: "kcal",
              percentOfDailyNeeds: 2.18,
            },
            {
              name: "Caffeine",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
          ],
        },
        {
          id: 14412,
          name: "water",
          amount: 50.0,
          unit: "milliliters",
          nutrients: [
            {
              name: "Fiber",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 3.02,
            },
            {
              name: "Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 1.48,
            },
            {
              name: "Protein",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 6.0,
            },
            {
              name: "Sodium",
              amount: 2.5,
              unit: "mg",
              percentOfDailyNeeds: 3.93,
            },
            {
              name: "Calcium",
              amount: 1.5,
              unit: "mg",
              percentOfDailyNeeds: 10.91,
            },
            {
              name: "Phosphorus",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 8.14,
            },
            {
              name: "Net Carbohydrates",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 1.92,
            },
            {
              name: "Carbohydrates",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 2.01,
            },
            {
              name: "Zinc",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 3.59,
            },
            {
              name: "Copper",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 1.78,
            },
            {
              name: "Magnesium",
              amount: 0.5,
              unit: "mg",
              percentOfDailyNeeds: 3.4,
            },
            {
              name: "Iron",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 3.69,
            },
            {
              name: "Manganese",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 3.89,
            },
            {
              name: "Fluoride",
              amount: 12.9,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Potassium",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 4.39,
            },
            {
              name: "Calories",
              amount: 0.0,
              unit: "kcal",
              percentOfDailyNeeds: 2.18,
            },
          ],
        },
        {
          id: 31015,
          name: "chilli",
          amount: 0.25,
          unit: "piece",
          nutrients: [
            {
              name: "Fiber",
              amount: 0.37,
              unit: "g",
              percentOfDailyNeeds: 3.02,
            },
            {
              name: "Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 1.48,
            },
            {
              name: "Protein",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 6.0,
            },
            {
              name: "Cholesterol",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 1.04,
            },
            {
              name: "Sodium",
              amount: 37.46,
              unit: "mg",
              percentOfDailyNeeds: 3.93,
            },
            {
              name: "Net Carbohydrates",
              amount: 0.38,
              unit: "g",
              percentOfDailyNeeds: 1.92,
            },
            {
              name: "Carbohydrates",
              amount: 0.75,
              unit: "g",
              percentOfDailyNeeds: 2.01,
            },
            {
              name: "Sugar",
              amount: 0.37,
              unit: "g",
              percentOfDailyNeeds: 5.03,
            },
            {
              name: "Saturated Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 3.36,
            },
            {
              name: "Vitamin C",
              amount: 1.35,
              unit: "mg",
              percentOfDailyNeeds: 3.07,
            },
            {
              name: "Calories",
              amount: 3.04,
              unit: "kcal",
              percentOfDailyNeeds: 2.18,
            },
          ],
        },
        {
          id: 11677,
          name: "shallot",
          amount: 0.25,
          unit: "piece",
          nutrients: [
            {
              name: "Choline",
              amount: 0.71,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Alcohol",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 100.0,
            },
            {
              name: "Vitamin B1",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 1.98,
            },
            {
              name: "Poly Unsaturated Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Fat",
              amount: 0.01,
              unit: "g",
              percentOfDailyNeeds: 1.48,
            },
            {
              name: "Cholesterol",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 1.04,
            },
            {
              name: "Vitamin B12",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 4.83,
            },
            {
              name: "Calcium",
              amount: 2.31,
              unit: "mg",
              percentOfDailyNeeds: 10.91,
            },
            {
              name: "Selenium",
              amount: 0.08,
              unit: "µg",
              percentOfDailyNeeds: 2.61,
            },
            {
              name: "Phosphorus",
              amount: 3.75,
              unit: "mg",
              percentOfDailyNeeds: 8.14,
            },
            {
              name: "Vitamin B3",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 0.52,
            },
            {
              name: "Net Carbohydrates",
              amount: 0.85,
              unit: "g",
              percentOfDailyNeeds: 1.92,
            },
            {
              name: "Vitamin D",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Folic Acid",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Folate",
              amount: 2.13,
              unit: "µg",
              percentOfDailyNeeds: 2.19,
            },
            {
              name: "Vitamin K",
              amount: 0.05,
              unit: "µg",
              percentOfDailyNeeds: 0.17,
            },
            {
              name: "Copper",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 1.78,
            },
            {
              name: "Iron",
              amount: 0.08,
              unit: "mg",
              percentOfDailyNeeds: 3.69,
            },
            {
              name: "Magnesium",
              amount: 1.31,
              unit: "mg",
              percentOfDailyNeeds: 3.4,
            },
            {
              name: "Lycopene",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Vitamin B5",
              amount: 0.02,
              unit: "mg",
              percentOfDailyNeeds: 3.24,
            },
            {
              name: "Manganese",
              amount: 0.02,
              unit: "mg",
              percentOfDailyNeeds: 3.89,
            },
            {
              name: "Protein",
              amount: 0.16,
              unit: "g",
              percentOfDailyNeeds: 6.0,
            },
            {
              name: "Fiber",
              amount: 0.2,
              unit: "g",
              percentOfDailyNeeds: 3.02,
            },
            {
              name: "Vitamin B2",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 6.81,
            },
            {
              name: "Sodium",
              amount: 0.75,
              unit: "mg",
              percentOfDailyNeeds: 3.93,
            },
            {
              name: "Mono Unsaturated Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Vitamin E",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 0.23,
            },
            {
              name: "Carbohydrates",
              amount: 1.05,
              unit: "g",
              percentOfDailyNeeds: 2.01,
            },
            {
              name: "Vitamin B6",
              amount: 0.02,
              unit: "mg",
              percentOfDailyNeeds: 2.89,
            },
            {
              name: "Sugar",
              amount: 0.49,
              unit: "g",
              percentOfDailyNeeds: 5.03,
            },
            {
              name: "Zinc",
              amount: 0.03,
              unit: "mg",
              percentOfDailyNeeds: 3.59,
            },
            {
              name: "Saturated Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 3.36,
            },
            {
              name: "Vitamin A",
              amount: 0.25,
              unit: "IU",
              percentOfDailyNeeds: 1.28,
            },
            {
              name: "Vitamin C",
              amount: 0.5,
              unit: "mg",
              percentOfDailyNeeds: 3.07,
            },
            {
              name: "Potassium",
              amount: 20.88,
              unit: "mg",
              percentOfDailyNeeds: 4.39,
            },
            {
              name: "Calories",
              amount: 4.5,
              unit: "kcal",
              percentOfDailyNeeds: 2.18,
            },
            {
              name: "Caffeine",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
          ],
        },
        {
          id: 2014,
          name: "roasted cumin seeds",
          amount: 0.25,
          unit: "teaspoon",
          nutrients: [
            {
              name: "Choline",
              amount: 0.12,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Alcohol",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 100.0,
            },
            {
              name: "Vitamin B1",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 1.98,
            },
            {
              name: "Poly Unsaturated Fat",
              amount: 0.02,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Fat",
              amount: 0.11,
              unit: "g",
              percentOfDailyNeeds: 1.48,
            },
            {
              name: "Cholesterol",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 1.04,
            },
            {
              name: "Vitamin B12",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 4.83,
            },
            {
              name: "Calcium",
              amount: 4.66,
              unit: "mg",
              percentOfDailyNeeds: 10.91,
            },
            {
              name: "Selenium",
              amount: 0.03,
              unit: "µg",
              percentOfDailyNeeds: 2.61,
            },
            {
              name: "Phosphorus",
              amount: 2.49,
              unit: "mg",
              percentOfDailyNeeds: 8.14,
            },
            {
              name: "Vitamin B3",
              amount: 0.02,
              unit: "mg",
              percentOfDailyNeeds: 0.52,
            },
            {
              name: "Net Carbohydrates",
              amount: 0.17,
              unit: "g",
              percentOfDailyNeeds: 1.92,
            },
            {
              name: "Vitamin D",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Folic Acid",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Folate",
              amount: 0.05,
              unit: "µg",
              percentOfDailyNeeds: 2.19,
            },
            {
              name: "Vitamin K",
              amount: 0.03,
              unit: "µg",
              percentOfDailyNeeds: 0.17,
            },
            {
              name: "Copper",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 1.78,
            },
            {
              name: "Iron",
              amount: 0.33,
              unit: "mg",
              percentOfDailyNeeds: 3.69,
            },
            {
              name: "Magnesium",
              amount: 1.83,
              unit: "mg",
              percentOfDailyNeeds: 3.4,
            },
            {
              name: "Lycopene",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Manganese",
              amount: 0.02,
              unit: "mg",
              percentOfDailyNeeds: 3.89,
            },
            {
              name: "Protein",
              amount: 0.09,
              unit: "g",
              percentOfDailyNeeds: 6.0,
            },
            {
              name: "Fiber",
              amount: 0.05,
              unit: "g",
              percentOfDailyNeeds: 3.02,
            },
            {
              name: "Vitamin B2",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 6.81,
            },
            {
              name: "Sodium",
              amount: 0.84,
              unit: "mg",
              percentOfDailyNeeds: 3.93,
            },
            {
              name: "Mono Unsaturated Fat",
              amount: 0.07,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Vitamin E",
              amount: 0.02,
              unit: "mg",
              percentOfDailyNeeds: 0.23,
            },
            {
              name: "Carbohydrates",
              amount: 0.22,
              unit: "g",
              percentOfDailyNeeds: 2.01,
            },
            {
              name: "Vitamin B6",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 2.89,
            },
            {
              name: "Sugar",
              amount: 0.01,
              unit: "g",
              percentOfDailyNeeds: 5.03,
            },
            {
              name: "Zinc",
              amount: 0.02,
              unit: "mg",
              percentOfDailyNeeds: 3.59,
            },
            {
              name: "Saturated Fat",
              amount: 0.01,
              unit: "g",
              percentOfDailyNeeds: 3.36,
            },
            {
              name: "Vitamin A",
              amount: 6.35,
              unit: "IU",
              percentOfDailyNeeds: 1.28,
            },
            {
              name: "Vitamin C",
              amount: 0.04,
              unit: "mg",
              percentOfDailyNeeds: 3.07,
            },
            {
              name: "Potassium",
              amount: 8.94,
              unit: "mg",
              percentOfDailyNeeds: 4.39,
            },
            {
              name: "Calories",
              amount: 1.88,
              unit: "kcal",
              percentOfDailyNeeds: 2.18,
            },
            {
              name: "Caffeine",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
          ],
        },
        {
          id: 2004,
          name: "corriander leaves",
          amount: 0.25,
          unit: "tablespoon",
          nutrients: [
            {
              name: "Alcohol",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 100.0,
            },
            {
              name: "Vitamin B1",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 1.98,
            },
            {
              name: "Poly Unsaturated Fat",
              amount: 0.01,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Fat",
              amount: 0.04,
              unit: "g",
              percentOfDailyNeeds: 1.48,
            },
            {
              name: "Cholesterol",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 1.04,
            },
            {
              name: "Calcium",
              amount: 4.17,
              unit: "mg",
              percentOfDailyNeeds: 10.91,
            },
            {
              name: "Vitamin B12",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 4.83,
            },
            {
              name: "Selenium",
              amount: 0.01,
              unit: "µg",
              percentOfDailyNeeds: 2.61,
            },
            {
              name: "Phosphorus",
              amount: 0.56,
              unit: "mg",
              percentOfDailyNeeds: 8.14,
            },
            {
              name: "Vitamin B3",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 0.52,
            },
            {
              name: "Net Carbohydrates",
              amount: 0.24,
              unit: "g",
              percentOfDailyNeeds: 1.92,
            },
            {
              name: "Vitamin D",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Folate",
              amount: 0.9,
              unit: "µg",
              percentOfDailyNeeds: 2.19,
            },
            {
              name: "Copper",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 1.78,
            },
            {
              name: "Folic Acid",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Iron",
              amount: 0.22,
              unit: "mg",
              percentOfDailyNeeds: 3.69,
            },
            {
              name: "Magnesium",
              amount: 0.6,
              unit: "mg",
              percentOfDailyNeeds: 3.4,
            },
            {
              name: "Manganese",
              amount: 0.04,
              unit: "mg",
              percentOfDailyNeeds: 3.89,
            },
            {
              name: "Protein",
              amount: 0.04,
              unit: "g",
              percentOfDailyNeeds: 6.0,
            },
            {
              name: "Fiber",
              amount: 0.13,
              unit: "g",
              percentOfDailyNeeds: 3.02,
            },
            {
              name: "Vitamin B2",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 6.81,
            },
            {
              name: "Sodium",
              amount: 0.12,
              unit: "mg",
              percentOfDailyNeeds: 3.93,
            },
            {
              name: "Carbohydrates",
              amount: 0.37,
              unit: "g",
              percentOfDailyNeeds: 2.01,
            },
            {
              name: "Mono Unsaturated Fat",
              amount: 0.01,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Zinc",
              amount: 0.02,
              unit: "mg",
              percentOfDailyNeeds: 3.59,
            },
            {
              name: "Vitamin B6",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 2.89,
            },
            {
              name: "Saturated Fat",
              amount: 0.01,
              unit: "g",
              percentOfDailyNeeds: 3.36,
            },
            {
              name: "Vitamin A",
              amount: 30.92,
              unit: "IU",
              percentOfDailyNeeds: 1.28,
            },
            {
              name: "Vitamin C",
              amount: 0.23,
              unit: "mg",
              percentOfDailyNeeds: 3.07,
            },
            {
              name: "Potassium",
              amount: 2.64,
              unit: "mg",
              percentOfDailyNeeds: 4.39,
            },
            {
              name: "Calories",
              amount: 1.57,
              unit: "kcal",
              percentOfDailyNeeds: 2.18,
            },
          ],
        },
        {
          id: 2047,
          name: "salt",
          amount: 0.25,
          unit: "dash",
          nutrients: [
            {
              name: "Choline",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Alcohol",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 100.0,
            },
            {
              name: "Vitamin B1",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 1.98,
            },
            {
              name: "Poly Unsaturated Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 1.48,
            },
            {
              name: "Cholesterol",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 1.04,
            },
            {
              name: "Vitamin B12",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 4.83,
            },
            {
              name: "Calcium",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 10.91,
            },
            {
              name: "Selenium",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 2.61,
            },
            {
              name: "Phosphorus",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 8.14,
            },
            {
              name: "Vitamin B3",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 0.52,
            },
            {
              name: "Net Carbohydrates",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 1.92,
            },
            {
              name: "Vitamin D",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Folic Acid",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Folate",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 2.19,
            },
            {
              name: "Vitamin K",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.17,
            },
            {
              name: "Copper",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 1.78,
            },
            {
              name: "Iron",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 3.69,
            },
            {
              name: "Magnesium",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 3.4,
            },
            {
              name: "Lycopene",
              amount: 0.0,
              unit: "µg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Vitamin B5",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 3.24,
            },
            {
              name: "Manganese",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 3.89,
            },
            {
              name: "Fluoride",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Protein",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 6.0,
            },
            {
              name: "Fiber",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 3.02,
            },
            {
              name: "Vitamin B2",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 6.81,
            },
            {
              name: "Sodium",
              amount: 9.69,
              unit: "mg",
              percentOfDailyNeeds: 3.93,
            },
            {
              name: "Mono Unsaturated Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Vitamin E",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 0.23,
            },
            {
              name: "Carbohydrates",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 2.01,
            },
            {
              name: "Vitamin B6",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 2.89,
            },
            {
              name: "Sugar",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 5.03,
            },
            {
              name: "Zinc",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 3.59,
            },
            {
              name: "Saturated Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 3.36,
            },
            {
              name: "Vitamin A",
              amount: 0.0,
              unit: "IU",
              percentOfDailyNeeds: 1.28,
            },
            {
              name: "Vitamin C",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 3.07,
            },
            {
              name: "Potassium",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 4.39,
            },
            {
              name: "Calories",
              amount: 0.0,
              unit: "kcal",
              percentOfDailyNeeds: 2.18,
            },
            {
              name: "Caffeine",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
          ],
        },
        {
          id: 10014412,
          name: "ice cubes",
          amount: 1.0,
          unit: "servings",
          nutrients: [
            {
              name: "Fiber",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 3.02,
            },
            {
              name: "Fat",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 1.48,
            },
            {
              name: "Protein",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 6.0,
            },
            {
              name: "Sodium",
              amount: 2.8,
              unit: "mg",
              percentOfDailyNeeds: 3.93,
            },
            {
              name: "Calcium",
              amount: 1.68,
              unit: "mg",
              percentOfDailyNeeds: 10.91,
            },
            {
              name: "Phosphorus",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 8.14,
            },
            {
              name: "Net Carbohydrates",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 1.92,
            },
            {
              name: "Carbohydrates",
              amount: 0.0,
              unit: "g",
              percentOfDailyNeeds: 2.01,
            },
            {
              name: "Zinc",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 3.59,
            },
            {
              name: "Copper",
              amount: 0.01,
              unit: "mg",
              percentOfDailyNeeds: 1.78,
            },
            {
              name: "Magnesium",
              amount: 0.56,
              unit: "mg",
              percentOfDailyNeeds: 3.4,
            },
            {
              name: "Iron",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 3.69,
            },
            {
              name: "Manganese",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 3.89,
            },
            {
              name: "Fluoride",
              amount: 14.45,
              unit: "mg",
              percentOfDailyNeeds: 0.0,
            },
            {
              name: "Potassium",
              amount: 0.0,
              unit: "mg",
              percentOfDailyNeeds: 4.39,
            },
            {
              name: "Calories",
              amount: 0.0,
              unit: "kcal",
              percentOfDailyNeeds: 2.18,
            },
          ],
        },
      ],
      caloricBreakdown: {
        percentProtein: 26.78,
        percentFat: 19.31,
        percentCarbs: 53.91,
      },
      weightPerServing: {
        amount: 176,
        unit: "g",
      },
    },
    summary:
      'You can never have too many beverage recipes, so give Spiced Lassi a try. One portion of this dish contains roughly <b>3g of protein</b>, <b>1g of fat</b>, and a total of <b>44 calories</b>. For <b>47 cents per serving</b>, this recipe <b>covers 3%</b> of your daily requirements of vitamins and minerals. This recipe serves 4. Not a lot of people really liked this Indian dish. This recipe from Foodista requires yogurt, water, corriander leaves, and ice cubes. 1 person has made this recipe and would make it again. From preparation to the plate, this recipe takes approximately <b>45 minutes</b>. It is a good option if you\'re following a <b>gluten free, lacto ovo vegetarian, and primal</b> diet. Overall, this recipe earns a <b>not so spectacular spoonacular score of 36%</b>. Try <a href="https://spoonacular.com/recipes/lassi-sweet-punjabi-lassi-how-to-make-lassi-488422">lassi , sweet punjabi lassi | how to make lassi</a>, <a href="https://spoonacular.com/recipes/spiced-lollipop-lamb-with-green-lassi-16346">Spiced Lollipop Lamb With Green Lassi</a>, and <a href="https://spoonacular.com/recipes/mango-lassi-or-aam-ki-lassi-how-to-make-mango-lassi-487676">Mango Lassi or Aam ki Lassi, How to make Mango Lassi</a> for similar recipes.',
    cuisines: ["Indian", "Asian"],
    dishTypes: ["beverage", "drink"],
    diets: ["gluten free", "lacto ovo vegetarian", "primal"],
    occasions: [],
    instructions:
      "Whisk yogurt with water until well-mixed.\nAdd chopped green chillis, shallots), dry-roasted cumin seeds, chopped corriander leaves, and a dash of salt. Mix.\nPour in glasses, add ice cubes. Serve!",
    analyzedInstructions: [
      {
        name: "",
        steps: [
          {
            number: 1,
            step: "Whisk yogurt with water until well-mixed.",
            ingredients: [
              {
                id: 1116,
                name: "yogurt",
                localizedName: "yogurt",
                image: "plain-yogurt.jpg",
              },
              {
                id: 14412,
                name: "water",
                localizedName: "water",
                image: "water.png",
              },
            ],
            equipment: [
              {
                id: 404661,
                name: "whisk",
                localizedName: "whisk",
                image:
                  "https://spoonacular.com/cdn/equipment_100x100/whisk.png",
              },
            ],
          },
          {
            number: 2,
            step: "Add chopped green chillis, shallots), dry-roasted cumin seeds, chopped corriander leaves, and a dash of salt.",
            ingredients: [
              {
                id: 31015,
                name: "green chili pepper",
                localizedName: "green chili pepper",
                image: "chili-peppers-green.jpg",
              },
              {
                id: 2014,
                name: "cumin seeds",
                localizedName: "cumin seeds",
                image: "ground-cumin.jpg",
              },
              {
                id: 11677,
                name: "shallot",
                localizedName: "shallot",
                image: "shallots.jpg",
              },
              {
                id: 2047,
                name: "salt",
                localizedName: "salt",
                image: "salt.jpg",
              },
            ],
            equipment: [],
          },
          {
            number: 3,
            step: "Mix.",
            ingredients: [],
            equipment: [],
          },
          {
            number: 4,
            step: "Pour in glasses, add ice cubes.",
            ingredients: [
              {
                id: 10014412,
                name: "ice cubes",
                localizedName: "ice cubes",
                image: "ice-cubes.png",
              },
            ],
            equipment: [],
          },
          {
            number: 5,
            step: "Serve!",
            ingredients: [],
            equipment: [],
          },
        ],
      },
    ],
    originalId: null,
    spoonacularScore: 0.3635493814945221,
    spoonacularSourceUrl: "https://spoonacular.com/spiced-lassi-660959",
  };
  const link = `https://api.spoonacular.com/recipes/${id}/information?apiKey=${key}&includeNutrition=true`;
  if (test) {
    return setData ? setData(exampleData) : exampleData;
  }
  try {
    const response = await fetch(link, { mode: "cors" });
    if (response.status >= 400) throw new Error("Server Error");
    const json = await response.json();
    return setData ? setData(json) : json;
  } catch (error) {
    return setError ? setError(error) : error;
  } finally {
    setLoading ? setLoading(false) : null;
  }
};

export default fetchRecipeData;
